[mgr]
prepend_keymap = [
    { on = [ "i", "y" ], run = "shell 'wl-copy < \"$@\"' --confirm", desc = "Copy image to clipboard" },
    { on = [ "i", "p" ], run = "shell --block 'read -p \"Имя файла: \" filename; wl-paste > $filename.png'", desc = "Paste image from clipboard" }
]
