general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    ignore_dbus_inhibit = true
}

listener {
    timeout = 840
    on-timeout = notify-send "Скоро выключусь!"
}

# Экран блокировки
listener {
    timeout = 900
    on-timeout = ~/.config/hypr/scripts/lock.sh --sleep
    on-resume = ~/.config/hypr/scripts/lock.sh --unsleep
}

# Мониторы
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
