general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    ignore_dbus_inhibit = true
}

listener {
    timeout = 540
    on-timeout = notify-send "Скоро выключусь!"
}

# Экран блокировки
listener {
    timeout = 600
    on-timeout = hyprctl switchxkblayout evision-rgb-keyboard 0 && hyprlock
}

# Мониторы
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
