windowrule = suppress_event = maximize mathc:class = .*

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:DP-1


windowrule {
  name = pavucontrol
  match:class = ^(org.pulseaudio.pavucontrol)$

  float = 1
  move = 480 60  
  size = 940 540
  monitor = 1
}

windowrule {
  name = Fix some dragging
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0

  no_focus = 1
}

windowrule {
  name = Telegram
  match:class = ^(org.telegram.desktop)$

  workspace = 4
}

windowrule {
  name = Firefox
  match:class = ^(firefox)$

  workspace = 5
}

windowrule {
  name = Spotify
  match:class = ^(spotify)$

  workspace = 6
}

windowrule {
  name = Steam
  match:class = ^(steam)$

  workspace = 2
}

windowrule {
  name = Список друзей steam
  match:title = ^(Список друзей)$

  float = 1
  size = 375 650
}

windowrule {
  name = Настройки Steam
  match:class = ^(steam)$
  match:title = ^(Настройки)$

  float = 1
}

windowrule {
  name = Библиотека
  match:class = ^(firefox)$
  match:title = ^(Библиотека)$

  float = 1
}

windowrule {
  name = v2rayN
  match:class = ^(v2rayN)$

  workspace = 9
}

windowrule {
    name = PortProton
    match:class = PortProton

    float = 1
}

windowrule {
    name = Thunderbird
    match:class = ^(org.mozilla.Thunderbird)$

    workspace = 10
}
